# Generated by Django 3.2.4 on 2021-08-13 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('student_id', models.IntegerField()),
                ('staff_comment_author', models.CharField(max_length=255)),
                ('staff_comment', models.TextField(blank=True)),
                ('is_banned', models.BooleanField(default=False)),
            ],
        ),
    ]
