# Generated by Django 3.2.4 on 2021-08-14 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20210813_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
