# Generated by Django 3.2.4 on 2021-08-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='duration',
            field=models.DurationField(blank=True),
        ),
    ]
