# Generated by Django 3.2.4 on 2021-08-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0003_alter_visit_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='duration',
        ),
        migrations.AddField(
            model_name='visit',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
