# Generated by Django 3.2.4 on 2021-08-23 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0004_auto_20210815_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
